Repository FACG5/unicornz, pull requests merged in 2018-11, with the labels that each got.

#51 Cards Component related to #33
  client/package-lock.json
  client/src/Components/Pages/WorkExpList/Cards/images/companyLogo.png
  client/src/Components/Pages/WorkExpList/Cards/index.js
  client/src/Components/Pages/WorkExpList/Cards/style.css
Labels: in-review

#52 Work Experience Details Page
  client/src/Components/Pages/WorkExpDetails/CompanyContact/images/email.png
  client/src/Components/Pages/WorkExpDetails/CompanyContact/images/facebook.png
  client/src/Components/Pages/WorkExpDetails/CompanyContact/images/instagram.png
  client/src/Components/Pages/WorkExpDetails/CompanyContact/images/telephone.png
  client/src/Components/Pages/WorkExpDetails/CompanyContact/images/website.png
  client/src/Components/Pages/WorkExpDetails/CompanyContact/index.js
  client/src/Components/Pages/WorkExpDetails/CompanyContact/style.css
  client/src/Components/Pages/WorkExpDetails/CompanyDescription/images/para-design.png
  client/src/Components/Pages/WorkExpDetails/CompanyDescription/index.js
  client/src/Components/Pages/WorkExpDetails/CompanyDescription/style.css
  client/src/Components/Pages/WorkExpDetails/WorkExpView/images/para-design.png
  client/src/Components/Pages/WorkExpDetails/WorkExpView/index.js
  client/src/Components/Pages/WorkExpDetails/WorkExpView/style.css
Labels: in-review

#64 Travis
  .travis.yml
  client/.gitignore
  client/src/Components/Pages/Category/images/ambassador.png
  client/src/Components/Pages/Category/images/company.png
  client/src/Components/Pages/Category/images/girl.png
  client/src/Components/Pages/Category/images/teacher.png
Labels: in-review

#63 Category page
  client/src/Components/Pages/Category/images/ambassador.png
  client/src/Components/Pages/Category/images/company.png
  client/src/Components/Pages/Category/images/girl.png
  client/src/Components/Pages/Category/images/teacher.png
  client/src/Components/Pages/Category/index.js
  client/src/Components/Pages/Category/style.css
Labels: In-Progress

#66 Category
  client/src/Components/App.js
  client/src/Components/Pages/Category/index.js
  client/src/Components/Pages/Category/style.css
Labels: in-review

#65 signup page
  .travis.yml
  client/package-lock.json
  client/package.json
  client/src/Components/App.js
  client/src/Components/CommonComponents/Inputs/index.js
  client/src/Components/CommonComponents/Inputs/style.css
  client/src/Components/Pages/SignUp/Category/index.js
  client/src/Components/Pages/SignUp/Category/style.css
  client/src/Components/Pages/SignUp/index.js
  package.json
Labels: In-Progress

#80 modified category
  client/src/Components/App.js
  client/src/Components/Pages/Category/index.js
  client/src/Components/Pages/Category/style.css
Labels: in-review

#79 work experience list
  client/src/Components/App.js
  client/src/Components/Pages/WorkExpList/Cards/index.js
  client/src/Components/Pages/WorkExpList/Cards/style.css
  client/src/Components/Pages/WorkExpList/images/companyLogo.png
  client/src/Components/Pages/WorkExpList/index.js
Labels: approved, in-review

#70 Database schema using sequelize
  .gitignore
  client/src/Components/App.js
  client/src/Components/CommonComponents/Footer/style.css
  client/src/Components/CommonComponents/Header/style.css
  package-lock.json
  package.json
  server/app.js
  server/authentication/authentication.js
  server/authentication/hashpassword.js
  server/dataBase/index.js
  server/index.js
  server/models/company.js
  server/models/connection.js
  server/models/girl.js
  server/models/index.js
  server/models/registration.js
  server/models/school.js
  server/models/work_experience.js
Labels: in-review, review changes

#96 Heroku
  client/src/Components/App.js
  config.js
  package-lock.json
  package.json
  server/models/connection.js
Labels: in-review

#97 Styling
  client/src/Components/App.js
  client/src/Components/CommonComponents/Footer/style.css
  client/src/Components/CommonComponents/Header/style.css
  client/src/Components/Pages/LandingPage/HeroSection/style.css
  client/src/Components/Pages/WorkExpList/Cards/style.css
  client/src/Components/Pages/WorkExpList/index.js
  client/src/Components/Pages/WorkExpList/style.css
Labels: in-review

#92 BasicDetails & PersonalDetails1 components
  client/package-lock.json
  client/package.json
  client/src/Components/Pages/Questionnaire/BasicDetails/index.js
  client/src/Components/Pages/Questionnaire/BasicDetails/style.css
  client/src/Components/Pages/Questionnaire/PersonalDetails1/index.js
  client/src/Components/Pages/Questionnaire/PersonalDetails1/style.css
Labels: in-review, waiting-review

#98 Styling
  client/src/Components/Pages/WorkExpDetails/CompanyContact/index.js
  client/src/Components/Pages/WorkExpDetails/CompanyContact/style.css
  client/src/Components/Pages/WorkExpDetails/CompanyDescription/index.js
  client/src/Components/Pages/WorkExpDetails/CompanyDescription/style.css
  client/src/Components/Pages/WorkExpDetails/WorkExpView/style.css
  client/src/Components/Pages/WorkExpDetails/images/para-design.png
  client/src/Components/Pages/WorkExpDetails/index.js
  client/src/Components/Pages/WorkExpDetails/style.css
  client/src/Components/Pages/WorkExpList/Cards/index.js
  client/src/Components/Pages/WorkExpList/Cards/style.css
Labels: in-review

#90 finalDetails component
  client/src/Components/Pages/Questionnaire/FinalDetails/index.js
  client/src/Components/Pages/Questionnaire/FinalDetails/style.css
  client/src/Components/Pages/Questionnaire/pic1.jpg
  client/src/Components/Pages/Questionnaire/pic2.jpeg
  client/src/Components/Pages/Questionnaire/pic3.jpeg
  client/src/Components/Pages/Questionnaire/pic4.jpg
Labels: In-Progress, bug, help wanted

#105 Fake Data
  server/models/fakeData.sql
Labels: In-Progress, approved

#109 work experience pages
  client/package-lock.json
  client/package.json
  client/src/Components/App.js
  client/src/Components/Pages/WorkExpDetails/CompanyContact/index.js
  client/src/Components/Pages/WorkExpDetails/index.js
  client/src/Components/Pages/WorkExpList/Cards/index.js
  client/src/Components/Pages/WorkExpList/Cards/style.css
  client/src/Components/Pages/WorkExpList/index.js
  client/src/Components/Pages/WorkExpList/style.css
  server/app.js
  server/controllers/index.js
  server/controllers/workExperienceList.js
  server/controllers/workexperienceDetails.js
  server/models/fakeData.sql
Labels: in-review

#113 Backend dash
  .eslintrc.json
  client/.eslintrc.json
  client/package.json
  client/src/Components/App.js
  client/src/Components/CommonComponents/Button/index.js
  client/src/Components/CommonComponents/Button/style.css
  client/src/Components/CommonComponents/Footer/index.js
  client/src/Components/CommonComponents/Footer/style.css
  client/src/Components/CommonComponents/Inputs/index.js
  client/src/Components/CommonComponents/SearchBar/index.js
  client/src/Components/Pages/Dashboard/ActiveJobs/index.js
  client/src/Components/Pages/Dashboard/ActiveJobs/style.css
  client/src/Components/Pages/Dashboard/MyActivety/index.js
  client/src/Components/Pages/Dashboard/PersonalInfo/index.js
  client/src/Components/Pages/Dashboard/PersonalInfo/style.css
  client/src/Components/Pages/Dashboard/PreviuosJobs/index.js
  client/src/Components/Pages/Dashboard/index.js
  client/src/Components/Pages/Questionnaire/PersonalDetails1/index.js
  client/src/Components/Pages/Questionnaire/index.js
  client/src/Components/Pages/WorkExpList/Cards/index.js
  client/src/Components/Pages/WorkExpList/index.js
  config.js
  package.json
  server/app.js
  server/controllers/dashBoard.js
  server/controllers/index.js
  server/controllers/search.js
  server/index.js
  server/models/company.js
  server/models/connection.js
  server/models/fakeData.sql
  server/models/girl.js
  server/models/index.js
  server/models/jobs.js
  server/models/registration.js
  server/models/school.js
  server/models/work_experience.js
Labels: in-review

#116 Dash style
  client/package.json
  client/src/Components/CommonComponents/Footer/style.css
  client/src/Components/Pages/Dashboard/ActiveJobs/index.js
  client/src/Components/Pages/Dashboard/ActiveJobs/style.css
  client/src/Components/Pages/Dashboard/MyActivety/style.css
  client/src/Components/Pages/Dashboard/PersonalInfo/style.css
  client/src/Components/Pages/Dashboard/images/star.svg
  client/src/Components/Pages/Dashboard/index.js
  client/src/Components/Pages/Dashboard/style.css
  client/src/Components/Pages/Questionnaire/PersonalDetails1/index.js
  client/src/Components/Pages/WorkExpList/Cards/index.js
  package.json
Labels: waiting-review

#114 Fake data
  client/package-lock.json
  client/package.json
  client/public/alertify.min.css
  client/public/bootstrap.min.css
  client/public/bootstrap.min.js
  client/public/index.html
  client/public/jquery-3.3.1.min.js
  client/public/semantic.min.css
  client/src/Components/App.css
  client/src/Components/App.js
  client/src/Components/CommonComponents/Button/style.css
  client/src/Components/CommonComponents/Header/index.js
  client/src/Components/CommonComponents/Inputs/style.css
  client/src/Components/Pages/Category/index.js
  client/src/Components/Pages/Dashboard/ActiveJobs/index.js
  client/src/Components/Pages/Dashboard/PersonalInfo/index.js
  client/src/Components/Pages/LandingPage/HeroSection/index.js
  client/src/Components/Pages/LandingPage/HeroSection/style.css
  client/src/Components/Pages/LandingPage/MissionSection/index.js
  client/src/Components/Pages/LandingPage/index.js
  client/src/Components/Pages/Login/index.js
  client/src/Components/Pages/Login/style.css
  client/src/Components/Pages/Questionnaire/FinalDetails/style.css
  client/src/Components/Pages/SignUp/index.js
  client/src/Components/Pages/SignUp/style.css
  client/src/Components/Pages/WorkExpDetails/index.js
  client/src/Components/Pages/WorkExpDetails/style.css
  client/src/Components/Pages/WorkExpList/Cards/index.js
  client/src/Components/Pages/WorkExpList/Cards/style.css
  client/src/Components/Pages/WorkExpList/index.js
  client/src/Components/Pages/workexpfill/bootstrap-grid.min.css
  client/src/Components/Pages/workexpfill/bootstrap-reboot.min.css
  client/src/Components/Pages/workexpfill/bootstrap.min.css
  client/src/Components/Pages/workexpfill/index.js
  client/src/Components/Pages/workexpfill/style.css
  config.js
  package-lock.json
  package.json
  server/app.js
  server/authentication/authentication.js
  server/controllers/company.js
  server/controllers/index.js
  server/controllers/school.js
  server/controllers/sign.js
  server/controllers/workexp.js
  server/index.js
  server/middleware/authorize.js
  server/models/company.js
  server/models/connection.js
  server/models/fakeData.sql
  server/models/girl.js
Labels: in-review

#117 modified path pages
  client/src/Components/App.js
  client/src/Components/CommonComponents/Header/index.js
  client/src/Components/Pages/Dashboard/PersonalInfo/index.js
  client/src/Components/Pages/Questionnaire/Wizard.js
  client/src/Components/Pages/Questionnaire/index.js
  client/src/Components/Pages/SignUp/index.js
  server/controllers/dashBoard.js
  server/controllers/sign.js
Labels: in-review

#119 workexperince details page
  client/src/Components/Pages/WorkExpDetails/CompanyContact/style.css
  client/src/Components/Pages/WorkExpDetails/CompanyDescription/style.css
  client/src/Components/Pages/WorkExpDetails/WorkExpView/style.css
  client/src/Components/Pages/WorkExpDetails/style.css
Labels: waiting-review

#128 Edit style
  client/src/Components/App.css
  client/src/Components/CommonComponents/Header/index.js
  client/src/Components/Pages/LandingPage/HeroSection/index.js
  client/src/Components/Pages/LandingPage/HeroSection/style.css
  client/src/Components/Pages/LandingPage/MissionSection/style.css
  client/src/Components/Pages/Login/index.js
  client/src/Components/Pages/Login/style.css
  client/src/Components/Pages/SignUp/index.js
  client/src/Components/Pages/SignUp/style.css
  client/src/index.css
Labels: waiting-review
