Repository FACG5/unicornz, pull requests merged in 2018-12, with the labels that each got.

#143 Questionnaire refactoring
  client/src/Components/Pages/Questionnaire/BasicDetails1/index.js
  client/src/Components/Pages/Questionnaire/BasicDetails2/index.js
  client/src/Components/Pages/Questionnaire/BasicDetails2/style.css
  client/src/Components/Pages/Questionnaire/FinalDetails/index.js
  client/src/Components/Pages/Questionnaire/PersonalDetails1/index.js
  client/src/Components/Pages/Questionnaire/PersonalDetails1/style.css
  client/src/Components/Pages/Questionnaire/PersonalDetails2/index.js
  client/src/Components/Pages/Questionnaire/PersonalDetails2/style.css
  client/src/Components/Pages/Questionnaire/Wizard.js
  client/src/Components/Pages/Questionnaire/index.js
  client/src/Components/Pages/Questionnaire/style.css
Labels: In-Progress, Refactoring sprint

#144 Fix Process
  .travis.yml
  client/src/Components/App.js
  client/src/Components/CommonComponents/Footer/index.js
  client/src/Components/CommonComponents/Header/index.js
  client/src/Components/Pages/Dashboard/PersonalInfo/index.js
  client/src/Components/Pages/Dashboard/index.js
  client/src/Components/Pages/Login/index.js
  client/src/Components/Pages/Login/style.css
  client/src/Components/Pages/Questionnaire/BasicDetails2/index.js
  client/src/Components/Pages/SignUp/index.js
  client/src/Components/Pages/WorkExpDetails/index.js
  client/src/Components/Pages/WorkExpList/Cards/index.js
  client/src/Components/Pages/WorkExpList/index.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/authentication/index.js
  server/controllers/dashBoard.js
  server/controllers/index.js
  server/controllers/login.js
  server/controllers/logout.js
  server/controllers/school.js
  server/controllers/search.js
  server/controllers/sign.js
  server/controllers/update.js
  server/index.js
Labels: in-review

#147 Fix signup authentication
  client/src/Components/App.js
  client/src/Components/Pages/Dashboard/PersonalInfo/index.js
  client/src/Components/Pages/Dashboard/index.js
  client/src/Components/Pages/LandingPage/index.js
  client/src/Components/Pages/Questionnaire/Wizard.js
  client/src/Components/Pages/Questionnaire/index.js
  client/src/Components/Pages/SignUp/index.js
  client/src/Components/Pages/WorkExpDetails/index.js
  config.js
  package-lock.json
  package.json
  server/authentication/authentication.js
  server/authentication/hashpassword.js
  server/controllers/school.js
  server/controllers/sign.js
Labels: in-review

#161 Autocomplete cities in united kingdom
  client/src/Components/Pages/Dashboard/ActiveJobs/index.js
Labels: Done, in-review

#145 Questionnaire
  client/src/Components/App.js
  client/src/Components/CommonComponents/Footer/style.css
  client/src/Components/CommonComponents/Header/index.js
  client/src/Components/Pages/Dashboard/ActiveJobs/index.js
  client/src/Components/Pages/Dashboard/PersonalInfo/index.js
  client/src/Components/Pages/Dashboard/UploadFile/index.js
  client/src/Components/Pages/Dashboard/UploadFile/style.css
  client/src/Components/Pages/Dashboard/index.js
  client/src/Components/Pages/Dashboard/style.css
  client/src/Components/Pages/Login/index.js
  client/src/Components/Pages/Questionnaire/BasicDetails1/index.js
  client/src/Components/Pages/Questionnaire/BasicDetails2/index.js
  client/src/Components/Pages/Questionnaire/FinalDetails/index.js
  client/src/Components/Pages/Questionnaire/PersonalDetails1/index.js
  client/src/Components/Pages/Questionnaire/PersonalDetails2/index.js
  client/src/Components/Pages/Questionnaire/Wizard.js
  client/src/Components/Pages/Questionnaire/index.js
  client/src/Components/Pages/SignUp/index.js
  client/src/Components/Pages/WorkExpDetails/index.js
  client/src/Components/Pages/WorkExpList/Cards/index.js
  client/src/Components/Pages/WorkExpList/index.js
  client/src/index.js
  config.js
  package-lock.json
  package.json
  q
  server/app.js
  server/controllers/index.js
  server/controllers/login.js
  server/controllers/logout.js
  server/controllers/questionnaire.js
  server/controllers/school.js
  server/controllers/sign.js
  server/controllers/update.js
  server/controllers/upload.js
  server/index.js
  server/middleware/upload.js
  server/models/fakeData.sql
  server/models/girl.js
  server/models/index.js
Labels: waiting-review

#172 modified work experience list when no companies
  client/src/Components/Pages/WorkExpList/index.js
Labels: in-review

#171 Percentage
  client/src/Components/Pages/Dashboard/PersonalInfo/index.js
  server/controllers/questionnaire.js
  server/controllers/sign.js
  server/models/girl.js
Labels: In-Progress

#176 add link to progress and delete my activity
  client/src/Components/Pages/Dashboard/PersonalInfo/index.js
  client/src/Components/Pages/Dashboard/index.js
Labels: waiting-review

#175 Modify
  client/src/Components/App.js
  client/src/Components/Pages/Dashboard/PersonalInfo/index.js
  client/src/Components/Pages/LandingPage/HeroSection/index.js
  client/src/Components/Pages/SignUp/index.js
  client/src/Components/Pages/SignUp/style.css
  client/src/Components/Pages/workexpfill/bootstrap-grid.min.css
  client/src/Components/Pages/workexpfill/bootstrap-reboot.min.css
  client/src/Components/Pages/workexpfill/bootstrap.min.css
  client/src/Components/Pages/workexpfill/index.js
  client/src/Components/Pages/workexpfill/style.css
  package-lock.json
  server/controllers/sign.js
  server/index.js
  server/models/fakeData.sql
  server/models/girl.js
Labels: waiting-review

#162 Form validation
  client/src/Components/Pages/Questionnaire/BasicDetails1/index.js
  client/src/Components/Pages/Questionnaire/BasicDetails2/index.js
  client/src/Components/Pages/Questionnaire/PersonalDetails1/index.js
  client/src/Components/Pages/Questionnaire/Wizard.js
  client/src/Components/Pages/Questionnaire/index.js
Labels: In-Progress

#180 fix card comp
  client/src/Components/Pages/WorkExpList/Cards/index.js
  server/index.js
  server/models/fakeData.sql
Labels: waiting-review

#182 profile page using react without css
  client/package-lock.json
  client/package.json
  client/src/Components/App.js
  client/src/Components/Pages/Dashboard/PersonalInfo/index.js
  client/src/Components/Pages/Profile/ProfComp/index.jsx
  client/src/Components/Pages/Profile/ProfComp/style.css
  client/src/Components/Pages/Profile/index.jsx
  client/src/Components/Pages/Profile/style.css
  package-lock.json
  server/controllers/index.js
  server/controllers/profile.js
  server/index.js
  server/models/girl.js
Labels: In-Progress
